/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Pablo
 */
public class Login extends javax.swing.JFrame {

    Menu me = new Menu();
    Conexion cc = new Conexion();
    Connection conectar = cc.conexion();
    ResultSet resultadoConsulta;
    private ButtonGroup bg;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        radios();
    }
    
    public void fecha(){
        String fecha = "";
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        fecha = ft.format(dNow);
        
    }
    
    void radios(){
        bg = new ButtonGroup();
        bg.add(rbnAdministrador);
        bg.add(rbnTrabajador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pswContraseña = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        btnAcceder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbnTrabajador = new javax.swing.JRadioButton();
        Logo = new javax.swing.JLabel();
        rbnAdministrador = new javax.swing.JRadioButton();
        Informacion = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 130, -1));
        getContentPane().add(pswContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, 30));

        btnAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/continue.png"))); // NOI18N
        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenido!!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        rbnTrabajador.setBackground(new java.awt.Color(204, 204, 204));
        rbnTrabajador.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        rbnTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        rbnTrabajador.setText("Trabajador");
        rbnTrabajador.setContentAreaFilled(false);
        getContentPane().add(rbnTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagenes base/Logo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 250));

        rbnAdministrador.setBackground(new java.awt.Color(51, 102, 255));
        rbnAdministrador.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        rbnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        rbnAdministrador.setSelected(true);
        rbnAdministrador.setText("Administrador");
        rbnAdministrador.setContentAreaFilled(false);
        getContentPane().add(rbnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        Informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info-icon.png"))); // NOI18N
        Informacion.setContentAreaFilled(false);
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });
        getContentPane().add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 40, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo azul.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 486, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int ax = JOptionPane.showConfirmDialog(null, "De verdad deseas salir de la aplicacion?");
        if(ax == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Regresa pronto","Exit",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }else if(ax == JOptionPane.NO_OPTION){
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        
        String fecha = "";
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        fecha = ft.format(dNow);
        
        
        String contra = new String(pswContraseña.getPassword());		
        
        if(txtUsuario.getText().equals("") || contra.equals("")){
                   JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos","Validación", JOptionPane.ERROR_MESSAGE);
                }else{
            
            
        
        if(rbnAdministrador.isSelected()==false && rbnTrabajador.isSelected()==false ){
            JOptionPane.showMessageDialog(null, "Porfavor seleccione su tipo de usuario!!","Validación",JOptionPane.ERROR_MESSAGE);
        }else{     
            
        if(rbnAdministrador.isSelected()==true){
               
            if((txtUsuario.getText().equals("Alfonso") || txtUsuario.getText().equals("Pablo") 
                || txtUsuario.getText().equals("Gustavo") || txtUsuario.getText().equals("Gerardo") 
                || txtUsuario.getText().equals("Fernanda") || txtUsuario.getText().equals("Anahi") 
                || txtUsuario.getText().equals("Ismael")) && contra.equals("TiendaElectronica")){
                MenuAdministrador mead = new MenuAdministrador();
                JOptionPane.showMessageDialog(null, "Bienvenido(a) Administrador "+txtUsuario.getText()+"!!!");
                mead.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos!!","Validación",JOptionPane.ERROR_MESSAGE);
            }
        }
        if(rbnTrabajador.isSelected()==true){
                try{
                      String consulta="SELECT usuario,contraseña FROM login WHERE usuario='"+txtUsuario.getText()+"' AND contraseña='"+contra+"'";

                      Statement sentencia=conectar.createStatement();
                      resultadoConsulta=sentencia.executeQuery(consulta);
                         while (resultadoConsulta.next()) {
                         
                                JOptionPane.showMessageDialog(null, "Bienvenido(a) "+txtUsuario.getText()+"!!!");
                                me.setVisible(true);
                                me.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                setVisible(false);
                             
                         }
                         
                         String nombre = txtUsuario.getText();
                         me.Menu(nombre, fecha);
                }catch (SQLException ex) {

                }
                
        }
        }
        }
        
    }//GEN-LAST:event_btnAccederActionPerformed

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Programa realizado para la administracion\n"
                + "y venta de productos electronicos\n\n"
                + "Administradores:\n"
                + "\t Alfonso\n"
                + "\t Pablo\n"
                + "\t Gustavo\n"
                + "\t Gerardo\n"
                + "\t Fernanda\n"
                + "\t Anahi\n"
                + "\t Ismael\n\n"
                + "Contraseña:\n"
                + "\t TiendaElectronica", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_InformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Informacion;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JRadioButton rbnAdministrador;
    private javax.swing.JRadioButton rbnTrabajador;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
