/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;
/**
 *
 * @author Pablo
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    
    public MenuAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBitacoras = new javax.swing.JButton();
        btnAltaBaja = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnElectronicos = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBitacoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/database_3.png"))); // NOI18N
        btnBitacoras.setToolTipText("Registro de Bitacoras");
        btnBitacoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBitacorasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBitacoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 134, -1));

        btnAltaBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/database_add.png"))); // NOI18N
        btnAltaBaja.setToolTipText("Modificación de Trabajadores");
        btnAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaBajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltaBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 124, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gnome_application_exit.png"))); // NOI18N
        btnSalir.setToolTipText("Regresar al login");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 140, 99));

        btnElectronicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TODO.jpg"))); // NOI18N
        btnElectronicos.setToolTipText("Modificación de Productos");
        btnElectronicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectronicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnElectronicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, 110));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo azul.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 410, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Login lo = new Login();
        lo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBitacorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBitacorasActionPerformed
        // TODO add your handling code here:
        Bitacoras bi = new Bitacoras();
        bi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBitacorasActionPerformed

    private void btnElectronicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectronicosActionPerformed
        // TODO add your handling code here:
        JFProductos pro = new JFProductos();
        pro.setBounds(200,50,1050,600);
        pro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnElectronicosActionPerformed

    private void btnAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaBajaActionPerformed
        // TODO add your handling code here:
        AltaBajaTrabajadores ta = new AltaBajaTrabajadores();
        ta.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAltaBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaBaja;
    private javax.swing.JButton btnBitacoras;
    private javax.swing.JButton btnElectronicos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
